name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  node_version: 16.14.2


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory: ./master-build
      run: docker build . --file Dockerfile --build-arg node_version=$node_version -t node-dotnet-sdk:$node_version
